import type { OutputFile } from "../pipeline/types";

// ---------------------------------------------------------------------------
// Generates app/layout.tsx — the root layout for the exported Next.js project
//
// Phase P7: emits site-wide metadata from Project.siteSettings when present
// (site name, description, language, favicon, theme color, robots). All
// values are escaped and optional values fall back deterministically.
// ---------------------------------------------------------------------------

export interface LayoutGeneratorOptions {
  projectName: string;
  projectDescription?: string;
  /** Phase P7 site settings (already normalized/validated). */
  siteSettings?: {
    siteName?: string;
    siteDescription?: string;
    language?: string;
    faviconPublicPath?: string;
    themeColor?: string;
    seoTitle?: string;
    seoDescription?: string;
    robotsIndex?: boolean;
    robotsFollow?: boolean;
  } | null;
}

export function generateLayout(options: LayoutGeneratorOptions): OutputFile {
  const settings = options.siteSettings ?? null;

  const siteName = settings?.siteName?.trim() || options.projectName;
  const description =
    settings?.siteDescription?.trim() ||
    settings?.seoDescription?.trim() ||
    options.projectDescription?.trim() ||
    "Generated by Buildora";
  const lang = settings?.language?.trim() || "en";

  const title = settings?.seoTitle?.trim() || siteName;

  // Robots — only emitted when the user explicitly opted out of indexing
  // (defaults are index+follow; emitting nothing means search engines use
  // their defaults).
  const robotsLines: string[] = [];
  if (settings?.robotsIndex === false || settings?.robotsFollow === false) {
    robotsLines.push(
      `  robots: { index: ${settings.robotsIndex !== false}, follow: ${settings.robotsFollow !== false} },`,
    );
  }

  const metadataLines: string[] = [
    `  title: "${escapeAttribute(title)}",`,
    `  description: "${escapeAttribute(description)}",`,
  ];

  if (settings?.faviconPublicPath) {
    metadataLines.push(
      `  icons: [{ rel: "icon", url: "${escapeAttribute(settings.faviconPublicPath)}" }],`,
    );
  }

  if (settings?.themeColor) {
    metadataLines.push(
      `  themeColor: "${escapeAttribute(settings.themeColor)}",`,
    );
  }

  metadataLines.push(...robotsLines);

  const content = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
${metadataLines.join("\n")}
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="${escapeAttribute(lang)}">
      <body className="min-h-screen antialiased">{children}</body>
    </html>
  );
}
`;

  return { path: "app/layout.tsx", content };
}

function escapeAttribute(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}
