import type { OutputFile } from "../pipeline/types";

// ---------------------------------------------------------------------------
// Generates app/layout.tsx — the root layout for the exported Next.js project
// ---------------------------------------------------------------------------

export interface LayoutGeneratorOptions {
  projectName: string;
  projectDescription?: string;
}

export function generateLayout(options: LayoutGeneratorOptions): OutputFile {
  const desc = options.projectDescription
    ? `"${escapeAttribute(options.projectDescription)}"`
    : `"Generated by Buildora"`;

  const content = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${escapeAttribute(options.projectName)}",
  description: ${desc},
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">{children}</body>
    </html>
  );
}
`;

  return { path: "app/layout.tsx", content };
}

function escapeAttribute(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}
