// ---------------------------------------------------------------------------
// Custom-block section generator (Phase P3)
//
// Emits a self-contained React component that renders a persisted BlockTree
// natively (no dangerouslySetInnerHTML, no raw imported source, no restored
// event handlers). The generated component mirrors the canvas BlockRenderer
// semantics: style tokens → inline styles, responsive overrides resolved by
// viewport width, safe links/images only.
//
// Phase P22-G — the generated component also mirrors the P22-G pure
// presentation layer (interactions/present.ts):
//   - declarative animations (fade/slide/scale/bounce/reveal/blur/rotate)
//     with bounded duration/delay/easing/repeat/direction
//   - load entrances, scroll-reveal entrances (IntersectionObserver),
//     and CSS hover/click-triggered animations
//   - hover/focus visual effects (allow-listed colors/shadow/scale only)
//   - safe click navigation (typed NavTarget → href via the routes map;
//     deferred kinds — toggle/modal/submit/custom — stay inert)
//   - scroll-to links (bounded known runtime helper, no user JS)
//   - prefers-reduced-motion disables entrance animation while keeping
//     hover/focus feedback and navigation
//
// Everything is embedded in the exported component as known, bounded helper
// code — no arbitrary user JavaScript is ever emitted.
// ---------------------------------------------------------------------------

import type { OutputFile } from "../../pipeline/types";
import { SANDBOX_POLICY } from "@/features/elements/custom-code/sandbox-policy";
import {
  HEARTBEAT_DEFAULTS,
  MAX_FRAME_HEIGHT_PX,
  MAX_RECOVERY_ATTEMPTS,
  MAX_RUNTIME_ERROR_MESSAGE_LENGTH,
  MAX_RUNTIME_ERROR_STACK_LENGTH,
  RUNTIME_MESSAGE_TYPES,
} from "@/features/elements/custom-code/constants";

export function generateCustomBlockComponent(): OutputFile {
  const content = `"use client";

// Generated by Buildora — renders an imported custom block design.
// The tree is native Buildora block data: never raw HTML, never scripts.

import { useEffect, useMemo, useRef, useState } from "react";

export interface BlockNode {
  id: string;
  type: string;
  parentId: string | null;
  children: string[];
  props: Record<string, unknown>;
  style: Record<string, unknown>;
  responsive: Record<string, Record<string, unknown>>;
  // Phase P22-F — optional Canva-first viewport overrides (base values live
  // in style; tablet/mobile override only what differs).
  viewport?: { tablet?: Record<string, unknown>; mobile?: Record<string, unknown> };
  // Phase P22-G — optional declarative animation + interaction (the P22-A
  // model verbatim; deferred kinds are inert in this bounded runtime).
  animation?: {
    trigger: string;
    type: string;
    durationMs?: number;
    delayMs?: number;
    easing?: string;
    repeat?: "none" | "infinite" | number;
    direction?: string;
  } | null;
  interaction?: {
    click?: { kind: string; target?: Record<string, unknown>; elementId?: string } | null;
    hover?: { color?: string; backgroundColor?: string; scale?: number; shadow?: string } | null;
    focus?: { color?: string; backgroundColor?: string; scale?: number; shadow?: string } | null;
    scroll?: { kind: string; animation?: Record<string, unknown> } | null;
    load?: Record<string, unknown> | null;
  } | null;
  // Phase P23-C — custom-code opt-in flag (data only; the validated sandbox
  // documents travel separately via the srcdocs prop).
  customCode?: { enabled?: boolean };
  visible: boolean;
  locked: boolean;
  hidden: boolean;
}

export interface BlockTree {
  rootIds: string[];
  nodes: Record<string, BlockNode>;
}

export interface CustomBlockProps {
  tree: BlockTree;
  name?: string;
  // Phase P22-G — page route map (pageId → href) used to resolve typed
  // NavTargets; unknown page ids resolve inert (never a dead/unsafe link).
  routes?: Record<string, string>;
  // Phase P23-C — validated sandbox documents for nodes with EXPLICITLY
  // ENABLED custom code (nodeId → srcdoc). Absent when no node qualifies.
  srcdocs?: Record<string, string>;
}

// ---- Safe URL policy (Buildora) ----
const SAFE_PROTOCOLS = new Set(["http:", "https:", "mailto:", "tel:", "#"]);

function isSafeLinkUrl(value: unknown): boolean {
  if (typeof value !== "string" || value.trim().length === 0) return false;
  const trimmed = value.trim();
  if (trimmed.startsWith("/")) return true;
  try {
    const url = new URL(trimmed, "https://buildora.local");
    return SAFE_PROTOCOLS.has(url.protocol);
  } catch {
    return false;
  }
}

function isSafeImageUrl(value: unknown): boolean {
  if (typeof value !== "string" || value.trim().length === 0) return false;
  const trimmed = value.trim();
  if (trimmed.startsWith("/")) return true;
  try {
    const url = new URL(trimmed, "https://buildora.local");
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function isSafeCssValue(value: string): boolean {
  const lower = value.toLowerCase();
  return (
    !lower.includes("javascript:") &&
    !lower.includes("vbscript:") &&
    !lower.includes("expression(") &&
    !lower.includes("behavior:") &&
    !lower.includes("binding:")
  );
}

const SHADOW_TOKENS: Record<string, string> = {
  small: "var(--shadow-sm, 0 1px 2px rgba(0,0,0,0.05))",
  medium: "var(--shadow-md, 0 4px 6px rgba(0,0,0,0.07))",
  large: "var(--shadow-lg, 0 10px 15px rgba(0,0,0,0.1))",
  none: "none",
};

const BREAKPOINTS: Array<[string, number]> = [
  ["sm", 640],
  ["md", 768],
  ["lg", 1024],
  ["xl", 1280],
  ["2xl", 1536],
];

// Phase P22-F — Canva-first viewport thresholds (mirror the editor: base
// desktop values live in style; tablet/mobile overrides win top-down).
const TABLET_MAX_WIDTH = 1024;
const MOBILE_MAX_WIDTH = 768;

function viewportOverrides(
  viewport: { tablet?: Record<string, unknown>; mobile?: Record<string, unknown> } | undefined,
  width: number,
): Record<string, unknown> {
  if (!viewport) return {};
  const merged: Record<string, unknown> = {};
  if (width <= TABLET_MAX_WIDTH && viewport.tablet) {
    Object.assign(merged, viewport.tablet);
  }
  if (width <= MOBILE_MAX_WIDTH && viewport.mobile) {
    Object.assign(merged, viewport.mobile);
  }
  return merged;
}

function styleToCss(style: Record<string, unknown>): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  for (const [key, value] of Object.entries(style)) {
    if (value === undefined || value === null) continue;
    if (key === "shadowDepth") {
      if (typeof value === "string" && value in SHADOW_TOKENS) out.boxShadow = SHADOW_TOKENS[value];
      continue;
    }
    if (typeof value === "string") {
      if (!isSafeCssValue(value)) continue;
      out[key] = value;
    } else if (typeof value === "number" && Number.isFinite(value)) {
      // Phase P22-C — opacity stores a beginner-friendly 0-100 value; CSS
      // opacity is 0-1 (mirrors styleTokensToCss in the editor).
      if (key === "opacity" && value > 1) {
        out[key] = value / 100;
      } else {
        out[key] = value;
      }
    }
  }
  return out;
}

function blockStyle(
  style: Record<string, unknown>,
  responsive: Record<string, Record<string, unknown>>,
  viewport: { tablet?: Record<string, unknown>; mobile?: Record<string, unknown> } | undefined,
  width: number,
): Record<string, string | number> {
  const base = styleToCss(style);
  const merged: Record<string, unknown> = {};
  for (const [name, min] of BREAKPOINTS) {
    if (min > width) continue;
    const overrides = responsive[name];
    if (overrides) Object.assign(merged, overrides);
  }
  Object.assign(merged, viewportOverrides(viewport, width));
  return { ...base, ...styleToCss(merged) };
}

function useViewportWidth(): number {
  const [width, setWidth] = useState(() => (typeof window === "undefined" ? 1440 : window.innerWidth));
  useEffect(() => {
    const onResize = () => setWidth(window.innerWidth);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);
  return width;
}

// ---------------------------------------------------------------------------
// Phase P22-G — declarative animation + interaction runtime
//
// Bounded, known helpers only. The P22-A model is the only vocabulary:
// deferred kinds (toggle / open-modal / submit-form / custom / start-animation
// / sticky / parallax) are inert — they never produce behavior or CSS.
// ---------------------------------------------------------------------------

const BA_KEYFRAMES: Record<string, string> = {
  fade: "@keyframes ba-fade { 0% { opacity: 0; } 100% { opacity: 1; } }",
  slide: "@keyframes ba-slide { 0% { opacity: 0; transform: translateY(24px); } 100% { opacity: 1; transform: translateY(0); } }",
  scale: "@keyframes ba-scale { 0% { opacity: 0; transform: scale(0.9); } 100% { opacity: 1; transform: scale(1); } }",
  bounce: "@keyframes ba-bounce { 0% { opacity: 0; transform: scale(0.9); } 50% { transform: scale(1.05); } 100% { opacity: 1; transform: scale(1); } }",
  reveal: "@keyframes ba-reveal { 0% { opacity: 0; clip-path: inset(0 0 100% 0); } 100% { opacity: 1; clip-path: inset(0 0 0 0); } }",
  blur: "@keyframes ba-blur { 0% { opacity: 0; filter: blur(8px); } 100% { opacity: 1; filter: blur(0px); } }",
  rotate: "@keyframes ba-rotate { 0% { opacity: 0; transform: rotate(-8deg) scale(0.95); } 100% { opacity: 1; transform: rotate(0deg) scale(1); } }",
};

// Entrance from-state (matches the editor's keyframeFromState so canvas and
// export show the same start before reveal/load).
const BA_FROM_STATE: Record<string, Record<string, string>> = {
  fade: { opacity: "0" },
  slide: { opacity: "0", transform: "translateY(24px)" },
  scale: { opacity: "0", transform: "scale(0.9)" },
  bounce: { opacity: "0", transform: "scale(0.9)" },
  reveal: { opacity: "0", clipPath: "inset(0 0 100% 0)" },
  blur: { opacity: "0", filter: "blur(8px)" },
  rotate: { opacity: "0", transform: "rotate(-8deg) scale(0.95)" },
};

const BA_DEFAULT_DURATION_MS = 500;
const BA_TRANSITION = "transform 150ms ease, color 150ms ease, background-color 150ms ease, box-shadow 150ms ease";

function baClampMs(value: unknown, fallback: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return fallback;
  return Math.min(Math.max(Math.round(value), 0), 60000);
}

function baAnimShorthand(anim: Record<string, unknown>): string {
  const type = typeof anim.type === "string" ? anim.type : "";
  const duration = baClampMs(anim.durationMs, BA_DEFAULT_DURATION_MS) + "ms";
  const delay = baClampMs(anim.delayMs, 0) + "ms";
  const easing = typeof anim.easing === "string" && anim.easing.length > 0 ? anim.easing : "ease";
  let iteration = "1";
  if (anim.repeat === "infinite") iteration = "infinite";
  else if (typeof anim.repeat === "number" && Number.isFinite(anim.repeat) && anim.repeat >= 0) iteration = String(Math.round(anim.repeat));
  const direction = anim.direction === "reverse" || anim.direction === "alternate" ? anim.direction : "normal";
  return "ba-" + type + " " + duration + " " + delay + " " + easing + " " + iteration + " " + direction + " both";
}

// The effective animation for a node (explicit animation > scroll reveal >
// load shortcut), exactly like the editor's effectiveAnimationForNode.
function baEffective(node: BlockNode): { anim: Record<string, unknown>; trigger: "load" | "scroll" | "hover" | "click" } | null {
  const animation = node.animation;
  if (animation && typeof animation === "object") {
    const trigger = animation.trigger;
    if (trigger === "load" || trigger === "scroll" || trigger === "viewport") {
      return { anim: animation, trigger: trigger === "load" ? "load" : "scroll" };
    }
    if (trigger === "hover" || trigger === "click") return { anim: animation, trigger };
    return null;
  }
  const scroll = node.interaction?.scroll;
  if (scroll && scroll.kind === "reveal" && scroll.animation && typeof scroll.animation === "object") {
    return { anim: scroll.animation, trigger: "scroll" };
  }
  const load = node.interaction?.load;
  if (load && typeof load === "object") return { anim: load, trigger: "load" };
  return null;
}

const BA_COLOR_RE = /^(?:#[0-9a-fA-F]{3,8}|(?:rgb|rgba|hsl|hsla|oklch|oklab|lab|lch|color)\([^()]*\)|var\(--[a-zA-Z0-9-]+(?:,[^)]+)?\)|transparent|currentColor|inherit|black|white|red|green|blue|gray|grey)$/;

function baSafeColor(value: unknown): boolean {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  return trimmed.length > 0 && trimmed.length <= 200 && BA_COLOR_RE.test(trimmed);
}

const BA_SHADOW_TOKENS: Record<string, string> = {
  none: "none",
  sm: "var(--shadow-sm, 0 1px 2px rgba(0,0,0,0.05))",
  md: "var(--shadow-md, 0 4px 6px rgba(0,0,0,0.07))",
  lg: "var(--shadow-lg, 0 10px 15px rgba(0,0,0,0.1))",
};

// Hover/focus visual effect rule — allow-listed values only (colors validated
// against the same color grammar as the editor; shadow via tokens; scale
// bounded). Deferred/unrecognized values are dropped.
function baEffectRule(id: string, pseudo: string, effect: Record<string, unknown>): string {
  const declarations: string[] = [];
  let transition = false;
  if (baSafeColor(effect.color)) {
    declarations.push("color: " + (effect.color as string).trim() + ";");
    transition = true;
  }
  if (baSafeColor(effect.backgroundColor)) {
    declarations.push("background-color: " + (effect.backgroundColor as string).trim() + ";");
    transition = true;
  }
  const shadow = typeof effect.shadow === "string" ? BA_SHADOW_TOKENS[effect.shadow] : undefined;
  if (shadow) {
    declarations.push("box-shadow: " + shadow + ";");
    transition = true;
  }
  if (typeof effect.scale === "number" && Number.isFinite(effect.scale) && effect.scale !== 1) {
    declarations.push("transform: scale(" + effect.scale + ");");
    transition = true;
  }
  if (declarations.length === 0) return "";
  const lines = ['[data-block-id="' + id + '"]' + pseudo + " {"];
  if (transition) lines.push("  transition: " + BA_TRANSITION + ";");
  for (const declaration of declarations) lines.push("  " + declaration);
  lines.push("}");
  return lines.join("\\n");
}

function baIsSafeNav(url: string): boolean {
  const lower = url.trim().toLowerCase();
  return (
    !lower.startsWith("javascript:") &&
    !lower.startsWith("vbscript:") &&
    !lower.startsWith("data:text/html")
  );
}

// Resolve a typed NavTarget against the exported route map (mirrors
// resolveNavTarget + isSafeNavUrl; unknown targets resolve inert).
function baResolveNav(
  target: Record<string, unknown>,
  routes: Record<string, string>,
): { href: string; kind: string; unresolved?: boolean } {
  const kind = target.kind;
  if (kind === "page") {
    const pageId = typeof target.pageId === "string" ? target.pageId : "";
    const href = routes[pageId];
    if (!href) return { href: "#", kind: "internal", unresolved: true };
    return { href, kind: "internal" };
  }
  if (kind === "section") {
    const sectionId = typeof target.sectionId === "string" ? target.sectionId : "";
    if (!sectionId) return { href: "#", kind: "internal", unresolved: true };
    if (typeof target.pageId === "string" && target.pageId && routes[target.pageId]) {
      return { href: routes[target.pageId] + "#" + sectionId, kind: "internal" };
    }
    return { href: "#" + sectionId, kind: "internal" };
  }
  if (kind === "external") {
    const url = typeof target.url === "string" ? target.url.trim() : "";
    if (!url || !baIsSafeNav(url)) return { href: "#", kind: "external", unresolved: true };
    return { href: url, kind: "external" };
  }
  if (kind === "email") {
    const to = typeof target.to === "string" ? target.to.trim() : "";
    if (!to) return { href: "#", kind: "email", unresolved: true };
    return { href: "mailto:" + to, kind: "email" };
  }
  if (kind === "phone") {
    const number = typeof target.number === "string" ? target.number.trim() : "";
    if (!number) return { href: "#", kind: "phone", unresolved: true };
    return { href: "tel:" + number, kind: "phone" };
  }
  if (kind === "back") return { href: "#", kind: "back" };
  return { href: "#", kind: "internal", unresolved: true };
}

// Resolve an element's click interaction (navigate / scroll-to). Deferred
// kinds and unresolvable targets return inert — never unsafe behavior.
function baResolveClick(
  node: BlockNode,
  tree: BlockTree,
  routes: Record<string, string>,
): { href?: string; kind?: string; scrollElementId?: string; back?: boolean; inert?: boolean } | null {
  const click = node.interaction?.click;
  if (!click || typeof click !== "object") return null;
  if (click.kind === "navigate" && click.target && typeof click.target === "object") {
    const resolved = baResolveNav(click.target as Record<string, unknown>, routes);
    if (resolved.unresolved) return { inert: true };
    return { href: resolved.href, kind: resolved.kind, back: resolved.kind === "back" };
  }
  if (click.kind === "scroll-to") {
    const elementId = typeof click.elementId === "string" ? click.elementId : "";
    if (!elementId || !tree.nodes[elementId]) return { inert: true };
    return { scrollElementId: elementId };
  }
  return { inert: true };
}

// Bounded known runtime helper for scroll-to (never user code).
function baScrollTo(elementId: string): void {
  const element = typeof document !== "undefined" ? document.getElementById(elementId) : null;
  if (!element) return;
  const reduce =
    typeof window.matchMedia === "function" &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  element.scrollIntoView(reduce ? {} : { behavior: "smooth" });
}

// Build the tree-level presentation CSS (keyframes + rules + reduced-motion).
function baTreePresentation(
  tree: BlockTree,
  routes: Record<string, string>,
): { cssText: string; needsReveal: boolean } {
  const keyframes = new Set<string>();
  const rules: string[] = [];
  let needsReveal = false;
  let hasEntrance = false;

  for (const id of Object.keys(tree.nodes).sort()) {
    const node = tree.nodes[id];
    if (!node) continue;

    const effective = baEffective(node);
    if (effective) {
      const type = typeof effective.anim.type === "string" ? effective.anim.type : "";
      const presetCss = BA_KEYFRAMES[type];
      if (presetCss) {
        keyframes.add(presetCss);
        if (effective.trigger === "scroll") {
          needsReveal = true;
          hasEntrance = true;
          rules.push(
            '[data-ba-reveal="' + node.id + '"].ba-reveal-in { animation: ' + baAnimShorthand(effective.anim) + "; }",
          );
        } else if (effective.trigger === "load") {
          hasEntrance = true;
        } else {
          // hover / click-triggered animations — pure CSS pseudo-class rules.
          const pseudo = effective.trigger === "hover" ? ":hover" : ":active";
          rules.push(
            '[data-block-id="' + node.id + '"]' + pseudo + " { animation: " + baAnimShorthand(effective.anim) + "; }",
          );
        }
      }
    }

    // Hover/focus visual effects (emitted regardless of entrance animation).
    const interaction = node.interaction;
    if (interaction?.hover && typeof interaction.hover === "object" && Object.keys(interaction.hover).length > 0) {
      const rule = baEffectRule(node.id, ":hover", interaction.hover as Record<string, unknown>);
      if (rule) rules.push(rule);
    }
    if (interaction?.focus && typeof interaction.focus === "object" && Object.keys(interaction.focus).length > 0) {
      const rule = baEffectRule(node.id, ":focus-visible", interaction.focus as Record<string, unknown>);
      if (rule) rules.push(rule);
    }
  }

  const parts: string[] = [];
  for (const kf of keyframes) parts.push(kf);
  for (const rule of rules) parts.push(rule);
  if (hasEntrance) {
    parts.push(
      "@media (prefers-reduced-motion: reduce) { [data-ba-anim=\\"load\\"] { animation: none !important; } [data-ba-anim=\\"scroll\\"] { animation: none !important; opacity: 1 !important; } }",
    );
  }
  return { cssText: parts.join("\\n"), needsReveal };
}

// Data attributes every node needs for interaction rules + scroll targets.
function nodeData(node: BlockNode, effective: ReturnType<typeof baEffective>): Record<string, string> {
  const data: Record<string, string> = {
    id: node.id,
    "data-block-id": node.id,
  };
  if (!effective) return data;
  const type = typeof effective.anim.type === "string" ? effective.anim.type : "";
  if (!BA_KEYFRAMES[type]) return data;
  if (effective.trigger === "load") data["data-ba-anim"] = "load";
  if (effective.trigger === "scroll") {
    data["data-ba-anim"] = "scroll";
    data["data-ba-reveal"] = node.id;
  }
  return data;
}

// Content wrapper for non-button nodes with a click interaction.
function InteractiveContent({
  action,
  children,
}: {
  action: { href?: string; kind?: string; scrollElementId?: string; back?: boolean };
  children: React.ReactNode;
}) {
  if (action.back) {
    return (
      <span
        role="link"
        tabIndex={0}
        data-ba-interaction="back"
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation();
          if (typeof window !== "undefined") window.history.back();
        }}
        onKeyDown={(e) => {
          if (e.key === "Enter" && typeof window !== "undefined") window.history.back();
        }}
      >
        {children}
      </span>
    );
  }
  if (action.href) {
    const external = action.kind === "external";
    return (
      <a
        href={action.href}
        data-ba-interaction="navigate"
        target={external ? "_blank" : undefined}
        rel={external ? "noopener noreferrer" : undefined}
      >
        {children}
      </a>
    );
  }
  if (action.scrollElementId) {
    return (
      <a
        href={"#" + action.scrollElementId}
        data-ba-interaction="scroll-to"
        onClick={(e) => {
          e.preventDefault();
          baScrollTo(action.scrollElementId!);
        }}
      >
        {children}
      </a>
    );
  }
  return <>{children}</>;
}

// Content node types that may carry a click interaction (mirrors the canvas
// BlockRenderer wrap-capable set — layout/navigation containers excluded so we
// never nest anchors or re-parent document structure).
function baWrapCapable(type: string): boolean {
  return (
    type !== "container" &&
    type !== "column" &&
    type !== "stack" &&
    type !== "row" &&
    type !== "grid" &&
    type !== "navbar" &&
    type !== "footer" &&
    type !== "form" &&
    type !== "menu" &&
    type !== "button" &&
    type !== "divider" &&
    type !== "spacer"
  );
}

function IconGlyph() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M12 3v18M3 12h18" opacity="0.35" />
      <path d="M12 8c1.8 0 3 1.2 3 3 0 1.6-1.4 2.6-3 4-1.6-1.4-3-2.4-3-4 0-1.8 1.2-3 3-3Z" />
    </svg>
  );
}

// Phase P23-C — the authoritative sandbox capability set (P23-B). The iframe
// grants allow-scripts ONLY: an opaque origin and no navigation/popup/form
// capabilities. Custom code runs ONLY inside this frame.
const CUSTOM_CODE_SANDBOX = ${JSON.stringify(SANDBOX_POLICY)};

// Phase P23-G — runtime protocol + heartbeat constants (mirror of the
// editor's custom-code constants so the exported runtime stays in lockstep
// with the tested controller semantics).
const CUSTOM_CODE_MESSAGE_TYPES = ${JSON.stringify(RUNTIME_MESSAGE_TYPES)};
const CUSTOM_CODE_HEARTBEAT = ${JSON.stringify(HEARTBEAT_DEFAULTS)};
const CUSTOM_CODE_MAX_RECOVERY_ATTEMPTS = ${JSON.stringify(MAX_RECOVERY_ATTEMPTS)};
const CUSTOM_CODE_MAX_FRAME_HEIGHT_PX = ${JSON.stringify(MAX_FRAME_HEIGHT_PX)};
const CUSTOM_CODE_MAX_ERROR_MESSAGE_LENGTH = ${JSON.stringify(MAX_RUNTIME_ERROR_MESSAGE_LENGTH)};
const CUSTOM_CODE_MAX_ERROR_STACK_LENGTH = ${JSON.stringify(MAX_RUNTIME_ERROR_STACK_LENGTH)};

// Phase P23-C/G — renders ONE validated custom-code srcdoc inside the
// sandboxed iframe. The frame is the only surface where custom code may
// execute; the srcdoc itself carries the internal sandbox CSP plus the
// child-side runtime shell (ready/height/error reporting).
//
// Phase P23-G — lifecycle hardening. Every mount owns a private runtime
// instance: the frame is keyed by its srcdoc, so ANY payload change remounts
// a fresh frame and the previous instance is disposed — stale frames,
// timers, and messages can never drive the new one. Within a mount the
// runtime validates every message (source identity + allow-listed payload),
// runs ONE bounded heartbeat, allows a bounded number of recoveries after
// the frame is declared unresponsive, and cleans up every listener/timer on
// unmount. This is a faithful mirror of the editor's tested controller
// (custom-code/runtime.ts) because exported files must be self-contained.
function CustomCodeFrame({ srcDoc }: { srcDoc: string }) {
  const iframeRef = useRef<HTMLIFrameElement | null>(null);
  const [frameHeight, setFrameHeight] = useState<number | null>(null);
  const [runtimeStatus, setRuntimeStatus] = useState("mounting");
  const [runtimeError, setRuntimeError] = useState(false);

  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    let disposed = false;
    let status: "mounting" | "ready" | "unresponsive" | "recovering" = "mounting";
    let lastSeen = Date.now();
    let misses = 0;
    let unresponsive = false;
    let recoveryAttempts = 0;
    let timer: ReturnType<typeof setTimeout> | undefined;

    const applyStatus = (next: "mounting" | "ready" | "unresponsive" | "recovering") => {
      status = next;
      setRuntimeStatus(next);
    };

    // One bounded heartbeat per runtime instance: a tick that finds more
    // than timeoutMs of silence counts a miss; maxMisses consecutive misses
    // declare the frame unresponsive (callback latches — no repeated firing).
    const tick = () => {
      if (disposed) return;
      if (Date.now() - lastSeen >= CUSTOM_CODE_HEARTBEAT.timeoutMs) {
        misses += 1;
        if (misses >= CUSTOM_CODE_HEARTBEAT.maxMisses && !unresponsive) {
          unresponsive = true;
          applyStatus("unresponsive");
        }
      } else {
        misses = 0;
      }
      timer = setTimeout(tick, CUSTOM_CODE_HEARTBEAT.intervalMs);
    };
    timer = setTimeout(tick, CUSTOM_CODE_HEARTBEAT.intervalMs);

    // Allow-listed payload validation (mirror of the editor protocol): exact
    // shapes only — unknown types, extra fields, and malformed values are
    // rejected before they can touch runtime state.
    const parseMessage = (data: unknown): { type: string; height?: number; error?: { message: string; stack?: string } } | null => {
      if (typeof data !== "object" || data === null || Array.isArray(data)) return null;
      const msg = data as Record<string, unknown>;
      const keys = Object.keys(msg);
      if (msg.type === CUSTOM_CODE_MESSAGE_TYPES.ready) {
        if (keys.length !== 1 || keys[0] !== "type") return null;
        return { type: msg.type };
      }
      if (msg.type === CUSTOM_CODE_MESSAGE_TYPES.height) {
        if (keys.length !== 2 || typeof msg.height !== "number" || !Number.isFinite(msg.height)) return null;
        return { type: msg.type, height: Math.min(Math.max(Math.round(msg.height), 0), CUSTOM_CODE_MAX_FRAME_HEIGHT_PX) };
      }
      if (msg.type === CUSTOM_CODE_MESSAGE_TYPES.error) {
        if (keys.length !== 2) return null;
        const raw = msg.error;
        if (typeof raw !== "object" || raw === null || Array.isArray(raw)) return null;
        const info = raw as Record<string, unknown>;
        const infoKeys = Object.keys(info);
        const hasStack = Object.prototype.hasOwnProperty.call(info, "stack");
        if (hasStack ? infoKeys.length !== 2 : infoKeys.length !== 1) return null;
        if (typeof info.message !== "string" || info.message.length === 0) return null;
        if (hasStack && typeof info.stack !== "string") return null;
        return {
          type: msg.type,
          error: hasStack
            ? { message: info.message.slice(0, CUSTOM_CODE_MAX_ERROR_MESSAGE_LENGTH), stack: (info.stack as string).slice(0, CUSTOM_CODE_MAX_ERROR_STACK_LENGTH) }
            : { message: info.message.slice(0, CUSTOM_CODE_MAX_ERROR_MESSAGE_LENGTH) },
        };
      }
      return null;
    };

    const onMessage = (event: MessageEvent) => {
      if (disposed) return;
      // The sandbox has an opaque origin, so origin checks are meaningless —
      // the source must be THIS frame's window, and each mount owns a private
      // instance (keyed remounts dispose the previous one).
      if (event.source !== iframe.contentWindow) return;
      const message = parseMessage(event.data);
      if (!message) return;

      if (message.type === CUSTOM_CODE_MESSAGE_TYPES.ready) {
        if (status === "unresponsive") {
          // Bounded recovery — a frame may come back a finite number of times,
          // then it is dead (timers stopped, messages ignored).
          if (recoveryAttempts >= CUSTOM_CODE_MAX_RECOVERY_ATTEMPTS) {
            if (timer !== undefined) clearTimeout(timer);
            timer = undefined;
            return;
          }
          recoveryAttempts += 1;
          unresponsive = false;
          applyStatus("recovering");
        } else if (status === "recovering") {
          applyStatus("ready");
        } else if (status === "mounting") {
          applyStatus("ready");
        }
        lastSeen = Date.now();
        misses = 0;
        return;
      }

      // height / error — only a frame that has anchored may send them; while
      // mounting, non-ready messages are stale/foreign and are fenced out.
      if (status === "mounting") return;
      if (status === "unresponsive") {
        if (recoveryAttempts >= CUSTOM_CODE_MAX_RECOVERY_ATTEMPTS) {
          if (timer !== undefined) clearTimeout(timer);
          timer = undefined;
          return;
        }
        recoveryAttempts += 1;
        unresponsive = false;
        applyStatus("recovering");
      } else if (status === "recovering") {
        applyStatus("ready");
      }
      lastSeen = Date.now();
      misses = 0;
      if (message.type === CUSTOM_CODE_MESSAGE_TYPES.height) {
        if (typeof message.height === "number") setFrameHeight(message.height);
      } else if (message.type === CUSTOM_CODE_MESSAGE_TYPES.error && message.error) {
        setRuntimeError(true);
      }
    };
    window.addEventListener("message", onMessage);

    return () => {
      disposed = true;
      window.removeEventListener("message", onMessage);
      if (timer !== undefined) clearTimeout(timer);
    };
  }, []);

  // Phase P23-H — safe observability: the mirror exposes ONLY bounded,
  // sanitized state (lifecycle status, whether an error was reported, and
  // the last validated height) as data attributes — never raw payloads or
  // exception data.
  return (
    <iframe
      ref={iframeRef}
      sandbox={CUSTOM_CODE_SANDBOX}
      srcDoc={srcDoc}
      title="Custom code"
      data-buildora-status={runtimeStatus}
      data-buildora-error={runtimeError ? "1" : undefined}
      data-buildora-height={frameHeight === null ? undefined : frameHeight}
      style={{
        width: "100%",
        border: "none",
        display: "block",
        ...(frameHeight === null ? {} : { height: frameHeight }),
      }}
    />
  );
}

function NodeView({ node, tree, width, routes, srcdocs }: { node: BlockNode; tree: BlockTree; width: number; routes: Record<string, string>; srcdocs: Record<string, string> }) {
  const css = blockStyle(node.style, node.responsive, node.viewport, width);

  // Phase P23-C — a node with EXPLICITLY ENABLED custom code renders inside
  // the sandboxed iframe, but only when BOTH conditions hold: the tree data
  // opts in (enabled === true) AND a validated srcdoc for this node was
  // computed at generation time (the srcdocs map). Data alone never executes
  // here — without a matching srcdoc the node renders exactly as before.
  const srcdoc = node.customCode?.enabled === true ? srcdocs[node.id] : undefined;
  if (srcdoc) {
    return (
      <div data-block-id={node.id} style={{ width: "100%", ...css }}>
        {/* Phase P23-G — keying by the srcdoc means any payload change
            (html/css/js/attributes/enabled) remounts a fresh iframe and
            disposes the previous runtime instance deterministically. */}
        <CustomCodeFrame key={srcdoc} srcDoc={srcdoc} />
      </div>
    );
  }

  // Phase P22-G — animation presentation (additive; nodes without animation
  // data render exactly as before).
  const effective = baEffective(node);
  if (effective) {
    const type = typeof effective.anim.type === "string" ? effective.anim.type : "";
    const preset = BA_KEYFRAMES[type] ? type : "";
    if (preset) {
      if (effective.trigger === "load") {
        css.animation = baAnimShorthand(effective.anim);
      } else if (effective.trigger === "scroll") {
        Object.assign(css, BA_FROM_STATE[preset]);
      }
      // hover/click triggers are pure CSS rules (baTreePresentation) — nothing
      // to inline.
    }
  }

  // Hover/focus effects add a transition so the feedback animates smoothly.
  const interaction = node.interaction;
  const hasEffect =
    (interaction?.hover && typeof interaction.hover === "object" && Object.keys(interaction.hover).length > 0) ||
    (interaction?.focus && typeof interaction.focus === "object" && Object.keys(interaction.focus).length > 0);
  if (hasEffect && css.transition === undefined) css.transition = BA_TRANSITION;

  const data = nodeData(node, effective);
  const children = node.children
    .map((id) => tree.nodes[id])
    .filter((child): child is BlockNode => !!child && child.visible !== false);

  const renderChildren = () =>
    children.map((child) => <NodeView key={child.id} node={child} tree={tree} width={width} routes={routes} srcdocs={srcdocs} />);

  const click = baResolveClick(node, tree, routes);
  const wrapContent = (elm: React.ReactNode): React.ReactNode => {
    if (baWrapCapable(node.type) && click && !click.inert) {
      return <InteractiveContent action={click}>{elm}</InteractiveContent>;
    }
    return elm;
  };

  const text = typeof node.props.text === "string" ? node.props.text : "";
  const href = isSafeLinkUrl(node.props.href) ? (node.props.href as string) : null;

  switch (node.type) {
    case "container":
    case "column":
    case "stack":
    case "row":
      return <div {...data} style={css}>{renderChildren()}</div>;
    case "grid": {
      const columns = typeof node.props.columns === "number" ? node.props.columns : 3;
      const gridStyle: Record<string, string | number> = {
        ...css,
        gridTemplateColumns: css.gridTemplateColumns ?? \`repeat(\${Math.min(Math.max(columns, 1), 6)}, minmax(0, 1fr))\`,
      };
      return <div {...data} style={gridStyle}>{renderChildren()}</div>;
    }
    case "divider":
      return <hr {...data} style={css} aria-hidden="true" />;
    case "spacer":
      return <div {...data} style={css} aria-hidden="true" />;
    case "heading": {
      const level = typeof node.props.level === "number" ? Math.min(Math.max(Math.round(node.props.level), 1), 6) : 2;
      const Tag = \`h\${level}\` as keyof React.JSX.IntrinsicElements;
      return wrapContent(<Tag {...data} style={css}>{text || "Heading"}</Tag>);
    }
    case "paragraph":
      return wrapContent(<p {...data} style={css}>{text || "Text"}</p>);
    case "button": {
      const style: Record<string, string | number> = { display: "inline-block", textDecoration: "none", ...css };
      const content = text || "Button";
      // A configured click interaction wins; otherwise fall back to the legacy
      // href prop (unchanged behavior for trees without interactions).
      if (click && !click.inert) {
        if (click.back) {
          return (
            <span
              role="button"
              tabIndex={0}
              {...data}
              style={style}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                if (typeof window !== "undefined") window.history.back();
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter" && typeof window !== "undefined") window.history.back();
              }}
            >
              {content}
            </span>
          );
        }
        if (click.scrollElementId) {
          return (
            <a
              href={"#" + click.scrollElementId}
              role="button"
              {...data}
              style={style}
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                baScrollTo(click.scrollElementId!);
              }}
            >
              {content}
            </a>
          );
        }
        if (click.href) {
          const external = click.kind === "external";
          return (
            <a
              href={click.href}
              {...data}
              style={style}
              target={external ? "_blank" : undefined}
              rel={external ? "noopener noreferrer" : undefined}
            >
              {content}
            </a>
          );
        }
        return <span {...data} style={style}>{content}</span>;
      }
      return href ? (
        <a href={href} {...data} style={style}>{content}</a>
      ) : (
        <span {...data} style={style}>{content}</span>
      );
    }
    case "image": {
      const src = isSafeImageUrl(node.props.src) ? (node.props.src as string) : "";
      const alt = typeof node.props.alt === "string" ? node.props.alt : "";
      if (!src) {
        return (
          <div {...data} style={{ ...css, display: "flex", alignItems: "center", justifyContent: "center", minHeight: "96px", background: "var(--muted, #f5f5f5)", color: "var(--muted-foreground, #737373)", fontSize: "0.75rem", border: "1px dashed var(--border, #e5e5e5)", borderRadius: "0.5rem" }}>
            Image
          </div>
        );
      }
      return wrapContent(<img {...data} src={src} alt={alt} loading="lazy" style={css} />);
    }
    case "video": {
      const src = isSafeImageUrl(node.props.src) ? (node.props.src as string) : "";
      if (!src) {
        return (
          <div {...data} style={{ ...css, display: "flex", alignItems: "center", justifyContent: "center", minHeight: "120px", background: "var(--muted, #f5f5f5)", color: "var(--muted-foreground, #737373)", fontSize: "0.75rem", borderRadius: "0.5rem" }}>
            Video
          </div>
        );
      }
      return wrapContent(<video {...data} src={src} muted playsInline style={css} />);
    }
    case "icon":
      return (
        <span {...data} style={{ ...css, display: "inline-flex" }}>
          <IconGlyph />
        </span>
      );
    case "badge":
      return wrapContent(<span {...data} style={css}>{text || "Badge"}</span>);
    case "form":
      return <form {...data} style={css} onSubmit={(e) => e.preventDefault()}>{renderChildren()}</form>;
    case "input": {
      const label = typeof node.props.label === "string" ? node.props.label : "Field";
      const placeholder = typeof node.props.placeholder === "string" ? node.props.placeholder : "";
      return (
        <label {...data} style={css}>{label}<input type="text" readOnly placeholder={placeholder} style={{ width: "100%", padding: "0.5rem 0.75rem", borderRadius: "0.375rem", border: "1px solid var(--border, #e5e5e5)", background: "var(--background, #fff)" }} /></label>
      );
    }
    case "textarea": {
      const label = typeof node.props.label === "string" ? node.props.label : "Message";
      const placeholder = typeof node.props.placeholder === "string" ? node.props.placeholder : "";
      return (
        <label {...data} style={css}>{label}<textarea readOnly placeholder={placeholder} style={{ width: "100%", padding: "0.5rem 0.75rem", borderRadius: "0.375rem", border: "1px solid var(--border, #e5e5e5)", minHeight: "6rem", background: "var(--background, #fff)" }} /></label>
      );
    }
    case "checkbox": {
      const label = typeof node.props.label === "string" ? node.props.label : "Checkbox";
      return (
        <label {...data} style={{ ...css, display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <input type="checkbox" checked={node.props.checked === true} readOnly />
          {label}
        </label>
      );
    }
    case "tabs":
    case "accordion":
      return wrapContent(<div {...data} style={css}>{renderChildren()}</div>);
    case "pricing-card":
      return (
        <div {...data} style={css}>
          {typeof node.props.price === "string" && <div style={{ fontSize: "1.75rem", fontWeight: 700 }}>{node.props.price}</div>}
          {typeof node.props.period === "string" && node.props.period && (
            <div style={{ color: "var(--muted-foreground, #737373)", fontSize: "0.8125rem" }}>{node.props.period}</div>
          )}
          {renderChildren()}
        </div>
      );
    case "review-card": {
      const rating = typeof node.props.rating === "number" ? node.props.rating : 0;
      return (
        <div {...data} style={css}>
          {rating > 0 && (
            <div aria-label={\`\${rating} out of 5 stars\`} style={{ display: "flex", gap: "0.125rem", color: "#f59e0b" }}>
              {Array.from({ length: Math.min(Math.round(rating), 5) }).map((_, i) => (
                <svg key={i} width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M12 2l2.9 6.3 6.9.8-5.1 4.7 1.4 6.8L12 17.2 5.9 20.6l1.4-6.8L2.2 9.1l6.9-.8L12 2z" />
                </svg>
              ))}
            </div>
          )}
          {renderChildren()}
        </div>
      );
    }
    case "navbar":
      return (
        <nav {...data} style={css}>
          {typeof node.props.logoText === "string" && node.props.logoText && (
            <span style={{ fontWeight: 700 }}>{node.props.logoText}</span>
          )}
          {renderChildren()}
        </nav>
      );
    case "footer":
      return <footer {...data} style={css}>{renderChildren()}</footer>;
    case "menu": {
      const links = Array.isArray(node.props.links) ? node.props.links : [];
      return (
        <ul {...data} style={{ ...css, listStyle: "none", margin: 0, padding: 0, display: "flex", flexWrap: "wrap", gap: "1rem" }}>
          {links.map((link, index) => {
            if (!link || typeof link !== "object") return null;
            const item = link as Record<string, unknown>;
            const linkHref = isSafeLinkUrl(item.href) ? (item.href as string) : "#";
            return (
              <li key={index}>
                <a href={linkHref} style={{ color: "inherit" }}>{typeof item.text === "string" ? item.text : "Link"}</a>
              </li>
            );
          })}
        </ul>
      );
    }
    case "card":
    case "feature-card":
    case "faq-item":
    case "team-member":
      return wrapContent(<div {...data} style={css}>{renderChildren()}</div>);
    default:
      return (
        <div {...data} style={{ ...css, border: "1px dashed var(--border, #e5e5e5)", borderRadius: "0.5rem", padding: "1rem" }}>
          {renderChildren()}
        </div>
      );
  }
}

// Phase P22-G — scroll-reveal IntersectionObserver (scoped to this tree).
function useScrollReveal(
  containerRef: React.RefObject<HTMLDivElement | null>,
  tree: BlockTree,
  active: boolean,
) {
  useEffect(() => {
    if (!active) return;
    const container = containerRef.current;
    if (!container) return;
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (!entry.isIntersecting) continue;
          entry.target.classList.add("ba-reveal-in");
          observer.unobserve(entry.target);
        }
      },
      { threshold: 0.15 },
    );
    container.querySelectorAll<HTMLElement>("[data-ba-reveal]").forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, [tree, active, containerRef]);
}

export function CustomBlock({ tree, name, routes = {}, srcdocs = {} }: CustomBlockProps) {
  const width = useViewportWidth();
  const presentation = useMemo(() => baTreePresentation(tree, routes), [tree, routes]);
  const containerRef = useRef<HTMLDivElement | null>(null);
  useScrollReveal(containerRef, tree, presentation.needsReveal);
  if (!tree || !tree.nodes) {
    return <section aria-label={name || "Imported design"} />;
  }
  const roots = tree.rootIds.map((id) => tree.nodes[id]).filter((node) => !!node && node.visible !== false);
  const content = roots.map((node) => (
    <NodeView key={node.id} node={node} tree={tree} width={width} routes={routes} srcdocs={srcdocs} />
  ));
  if (presentation.needsReveal) {
    return (
      <section aria-label={name || "Imported design"}>
        {presentation.cssText && <style>{presentation.cssText}</style>}
        <div ref={containerRef} data-ba-tree="1">{content}</div>
      </section>
    );
  }
  return (
    <section aria-label={name || "Imported design"}>
      {presentation.cssText && <style>{presentation.cssText}</style>}
      {content}
    </section>
  );
}
`;

  return { path: "components/sections/custom-block.tsx", content };
}
