// ---------------------------------------------------------------------------
// Custom-block section generator (Phase P3)
//
// Emits a self-contained React component that renders a persisted BlockTree
// natively (no dangerouslySetInnerHTML, no raw imported source, no restored
// event handlers). The generated component mirrors the canvas BlockRenderer
// semantics: style tokens → inline styles, responsive overrides resolved by
// viewport width, safe links/images only.
// ---------------------------------------------------------------------------

import type { OutputFile } from "../../pipeline/types";

export function generateCustomBlockComponent(): OutputFile {
  const content = `"use client";

// Generated by Buildora — renders an imported custom block design.
// The tree is native Buildora block data: never raw HTML, never scripts.

import { useEffect, useState } from "react";

export interface BlockNode {
  id: string;
  type: string;
  parentId: string | null;
  children: string[];
  props: Record<string, unknown>;
  style: Record<string, unknown>;
  responsive: Record<string, Record<string, unknown>>;
  visible: boolean;
  locked: boolean;
  hidden: boolean;
}

export interface BlockTree {
  rootIds: string[];
  nodes: Record<string, BlockNode>;
}

export interface CustomBlockProps {
  tree: BlockTree;
  name?: string;
}

// ---- Safe URL policy (Buildora) ----
const SAFE_PROTOCOLS = new Set(["http:", "https:", "mailto:", "tel:", "#"]);

function isSafeLinkUrl(value: unknown): boolean {
  if (typeof value !== "string" || value.trim().length === 0) return false;
  const trimmed = value.trim();
  if (trimmed.startsWith("/")) return true;
  try {
    const url = new URL(trimmed, "https://buildora.local");
    return SAFE_PROTOCOLS.has(url.protocol);
  } catch {
    return false;
  }
}

function isSafeImageUrl(value: unknown): boolean {
  if (typeof value !== "string" || value.trim().length === 0) return false;
  const trimmed = value.trim();
  if (trimmed.startsWith("/")) return true;
  try {
    const url = new URL(trimmed, "https://buildora.local");
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function isSafeCssValue(value: string): boolean {
  const lower = value.toLowerCase();
  return (
    !lower.includes("javascript:") &&
    !lower.includes("vbscript:") &&
    !lower.includes("expression(") &&
    !lower.includes("behavior:") &&
    !lower.includes("binding:")
  );
}

const SHADOW_TOKENS: Record<string, string> = {
  small: "var(--shadow-sm, 0 1px 2px rgba(0,0,0,0.05))",
  medium: "var(--shadow-md, 0 4px 6px rgba(0,0,0,0.07))",
  large: "var(--shadow-lg, 0 10px 15px rgba(0,0,0,0.1))",
  none: "none",
};

const BREAKPOINTS: Array<[string, number]> = [
  ["sm", 640],
  ["md", 768],
  ["lg", 1024],
  ["xl", 1280],
  ["2xl", 1536],
];

function styleToCss(style: Record<string, unknown>): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  for (const [key, value] of Object.entries(style)) {
    if (value === undefined || value === null) continue;
    if (key === "shadowDepth") {
      if (typeof value === "string" && value in SHADOW_TOKENS) out.boxShadow = SHADOW_TOKENS[value];
      continue;
    }
    if (typeof value === "string") {
      if (!isSafeCssValue(value)) continue;
      out[key] = value;
    } else if (typeof value === "number" && Number.isFinite(value)) {
      out[key] = value;
    }
  }
  return out;
}

function blockStyle(
  style: Record<string, unknown>,
  responsive: Record<string, Record<string, unknown>>,
  width: number,
): Record<string, string | number> {
  const base = styleToCss(style);
  const merged: Record<string, unknown> = {};
  for (const [name, min] of BREAKPOINTS) {
    if (min > width) continue;
    const overrides = responsive[name];
    if (overrides) Object.assign(merged, overrides);
  }
  return { ...base, ...styleToCss(merged) };
}

function useViewportWidth(): number {
  const [width, setWidth] = useState(() => (typeof window === "undefined" ? 1440 : window.innerWidth));
  useEffect(() => {
    const onResize = () => setWidth(window.innerWidth);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);
  return width;
}

function IconGlyph() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <path d="M12 3v18M3 12h18" opacity="0.35" />
      <path d="M12 8c1.8 0 3 1.2 3 3 0 1.6-1.4 2.6-3 4-1.6-1.4-3-2.4-3-4 0-1.8 1.2-3 3-3Z" />
    </svg>
  );
}

function NodeView({ node, tree, width }: { node: BlockNode; tree: BlockTree; width: number }) {
  const css = blockStyle(node.style, node.responsive, width);
  const children = node.children
    .map((id) => tree.nodes[id])
    .filter((child): child is BlockNode => !!child && child.visible !== false);

  const renderChildren = () =>
    children.map((child) => <NodeView key={child.id} node={child} tree={tree} width={width} />);

  const text = typeof node.props.text === "string" ? node.props.text : "";
  const href = isSafeLinkUrl(node.props.href) ? (node.props.href as string) : null;

  switch (node.type) {
    case "container":
    case "column":
    case "stack":
    case "row":
      return <div style={css}>{renderChildren()}</div>;
    case "grid": {
      const columns = typeof node.props.columns === "number" ? node.props.columns : 3;
      const gridStyle: Record<string, string | number> = {
        ...css,
        gridTemplateColumns: css.gridTemplateColumns ?? \`repeat(\${Math.min(Math.max(columns, 1), 6)}, minmax(0, 1fr))\`,
      };
      return <div style={gridStyle}>{renderChildren()}</div>;
    }
    case "divider":
      return <hr style={css} aria-hidden="true" />;
    case "spacer":
      return <div style={css} aria-hidden="true" />;
    case "heading": {
      const level = typeof node.props.level === "number" ? Math.min(Math.max(Math.round(node.props.level), 1), 6) : 2;
      const Tag = \`h\${level}\` as keyof React.JSX.IntrinsicElements;
      return <Tag style={css}>{text || "Heading"}</Tag>;
    }
    case "paragraph":
      return <p style={css}>{text || "Text"}</p>;
    case "button": {
      const style: Record<string, string | number> = { display: "inline-block", textDecoration: "none", ...css };
      const content = text || "Button";
      return href ? (
        <a href={href} style={style}>{content}</a>
      ) : (
        <span style={style}>{content}</span>
      );
    }
    case "image": {
      const src = isSafeImageUrl(node.props.src) ? (node.props.src as string) : "";
      const alt = typeof node.props.alt === "string" ? node.props.alt : "";
      if (!src) {
        return (
          <div style={{ ...css, display: "flex", alignItems: "center", justifyContent: "center", minHeight: "96px", background: "var(--muted, #f5f5f5)", color: "var(--muted-foreground, #737373)", fontSize: "0.75rem", border: "1px dashed var(--border, #e5e5e5)", borderRadius: "0.5rem" }}>
            Image
          </div>
        );
      }
      return <img src={src} alt={alt} loading="lazy" style={css} />;
    }
    case "video": {
      const src = isSafeImageUrl(node.props.src) ? (node.props.src as string) : "";
      if (!src) {
        return (
          <div style={{ ...css, display: "flex", alignItems: "center", justifyContent: "center", minHeight: "120px", background: "var(--muted, #f5f5f5)", color: "var(--muted-foreground, #737373)", fontSize: "0.75rem", borderRadius: "0.5rem" }}>
            Video
          </div>
        );
      }
      return <video src={src} muted playsInline style={css} />;
    }
    case "icon":
      return (
        <span style={{ ...css, display: "inline-flex" }}>
          <IconGlyph />
        </span>
      );
    case "badge":
      return <span style={css}>{text || "Badge"}</span>;
    case "form":
      return <form style={css} onSubmit={(e) => e.preventDefault()}>{renderChildren()}</form>;
    case "input": {
      const label = typeof node.props.label === "string" ? node.props.label : "Field";
      const placeholder = typeof node.props.placeholder === "string" ? node.props.placeholder : "";
      return (
        <label style={css}>{label}<input type="text" readOnly placeholder={placeholder} style={{ width: "100%", padding: "0.5rem 0.75rem", borderRadius: "0.375rem", border: "1px solid var(--border, #e5e5e5)", background: "var(--background, #fff)" }} /></label>
      );
    }
    case "textarea": {
      const label = typeof node.props.label === "string" ? node.props.label : "Message";
      const placeholder = typeof node.props.placeholder === "string" ? node.props.placeholder : "";
      return (
        <label style={css}>{label}<textarea readOnly placeholder={placeholder} style={{ width: "100%", padding: "0.5rem 0.75rem", borderRadius: "0.375rem", border: "1px solid var(--border, #e5e5e5)", minHeight: "6rem", background: "var(--background, #fff)" }} /></label>
      );
    }
    case "checkbox": {
      const label = typeof node.props.label === "string" ? node.props.label : "Checkbox";
      return (
        <label style={{ ...css, display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <input type="checkbox" checked={node.props.checked === true} readOnly />
          {label}
        </label>
      );
    }
    case "tabs":
    case "accordion":
      return <div style={css}>{renderChildren()}</div>;
    case "pricing-card":
      return (
        <div style={css}>
          {typeof node.props.price === "string" && <div style={{ fontSize: "1.75rem", fontWeight: 700 }}>{node.props.price}</div>}
          {typeof node.props.period === "string" && node.props.period && (
            <div style={{ color: "var(--muted-foreground, #737373)", fontSize: "0.8125rem" }}>{node.props.period}</div>
          )}
          {renderChildren()}
        </div>
      );
    case "review-card": {
      const rating = typeof node.props.rating === "number" ? node.props.rating : 0;
      return (
        <div style={css}>
          {rating > 0 && (
            <div aria-label={\`\${rating} out of 5 stars\`} style={{ display: "flex", gap: "0.125rem", color: "#f59e0b" }}>
              {Array.from({ length: Math.min(Math.round(rating), 5) }).map((_, i) => (
                <svg key={i} width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  <path d="M12 2l2.9 6.3 6.9.8-5.1 4.7 1.4 6.8L12 17.2 5.9 20.6l1.4-6.8L2.2 9.1l6.9-.8L12 2z" />
                </svg>
              ))}
            </div>
          )}
          {renderChildren()}
        </div>
      );
    }
    case "navbar":
      return (
        <nav style={css}>
          {typeof node.props.logoText === "string" && node.props.logoText && (
            <span style={{ fontWeight: 700 }}>{node.props.logoText}</span>
          )}
          {renderChildren()}
        </nav>
      );
    case "footer":
      return <footer style={css}>{renderChildren()}</footer>;
    case "menu": {
      const links = Array.isArray(node.props.links) ? node.props.links : [];
      return (
        <ul style={{ ...css, listStyle: "none", margin: 0, padding: 0, display: "flex", flexWrap: "wrap", gap: "1rem" }}>
          {links.map((link, index) => {
            if (!link || typeof link !== "object") return null;
            const item = link as Record<string, unknown>;
            const linkHref = isSafeLinkUrl(item.href) ? (item.href as string) : "#";
            return (
              <li key={index}>
                <a href={linkHref} style={{ color: "inherit" }}>{typeof item.text === "string" ? item.text : "Link"}</a>
              </li>
            );
          })}
        </ul>
      );
    }
    case "card":
    case "feature-card":
    case "faq-item":
    case "team-member":
      return <div style={css}>{renderChildren()}</div>;
    default:
      return (
        <div style={{ ...css, border: "1px dashed var(--border, #e5e5e5)", borderRadius: "0.5rem", padding: "1rem" }}>
          {renderChildren()}
        </div>
      );
  }
}

export function CustomBlock({ tree, name }: CustomBlockProps) {
  const width = useViewportWidth();
  if (!tree || !tree.nodes) {
    return <section aria-label={name || "Imported design"} />;
  }
  const roots = tree.rootIds.map((id) => tree.nodes[id]).filter((node) => !!node && node.visible !== false);
  return (
    <section aria-label={name || "Imported design"}>
      {roots.map((node) => (
        <NodeView key={node.id} node={node} tree={tree} width={width} />
      ))}
    </section>
  );
}
`;

  return { path: "components/sections/custom-block.tsx", content };
}
