// ---------------------------------------------------------------------------
// scrollSectionIntoView — narrow interaction helper
//
// Scrolls the canvas element for a section into view using the stable
// `data-section-id` attribute. No direct DOM querying scattered across
// components, no focus theft, no store mutation, no crash when the element
// is missing. Smooth scrolling respects the user's reduced-motion preference.
//
// The container argument is optional for testability — when omitted, the
// query runs against the whole document.
// ---------------------------------------------------------------------------

export interface ScrollSectionIntoViewOptions {
  /** Scroll container; defaults to the nearest scrollable ancestor. */
  container?: HTMLElement | null;
  block?: ScrollLogicalPosition;
  /** Override reduced-motion detection (for tests). */
  reducedMotion?: boolean;
}

/** Testable wrapper: find the canvas element for a section by data attribute. */
export function findSectionElement(
  sectionId: string,
  container?: HTMLElement | null,
): HTMLElement | null {
  const root = container ?? document;
  return root.querySelector<HTMLElement>(`[data-section-id="${cssEscape(sectionId)}"]`);
}

/**
 * Scroll the canvas section element into view. Returns true when the element
 * was found and scrolled; false when missing (callers can safely ignore).
 */
export function scrollSectionIntoView(
  sectionId: string,
  options?: ScrollSectionIntoViewOptions,
): boolean {
  const element = findSectionElement(sectionId, options?.container);
  if (!element) return false;

  const prefersReduced =
    options?.reducedMotion ??
    (typeof window !== "undefined" &&
      typeof window.matchMedia === "function" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches);

  element.scrollIntoView({
    behavior: prefersReduced ? "auto" : "smooth",
    block: options?.block ?? "center",
  });

  return true;
}

/**
 * Scroll a row in the structure panel into view. Uses the stable
 * `data-structure-row-id` attribute within the panel container.
 */
export function scrollStructureRowIntoView(
  rowId: string,
  container: HTMLElement | null,
): boolean {
  if (!container) return false;
  const row = container.querySelector<HTMLElement>(
    `[data-structure-row-id="${cssEscape(rowId)}"]`,
  );
  if (!row) return false;

  const prefersReduced =
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  row.scrollIntoView({
    behavior: prefersReduced ? "auto" : "smooth",
    block: "nearest",
  });
  return true;
}

// ---------------------------------------------------------------------------
// Minimal CSS.escape polyfill (IDs are generated and safe, but defensive)
// ---------------------------------------------------------------------------

function cssEscape(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  // Fallback: IDs generated by the app never contain quotes/backslashes, but
  // escape them defensively for arbitrary imported data.
  return value.replace(/([^a-zA-Z0-9_-])/g, "\\$1");
}
