// ---------------------------------------------------------------------------
// Export — site-level and page-level metadata generation (Phase P7)
// ---------------------------------------------------------------------------

import { describe, it, expect } from "vitest";
import { generateLayout } from "../generators/layout-generator";
import { generatePageFile } from "../generators/page-generator";
import { buildExportAssetManifest } from "../generators/asset-export-manifest";
import { computePageRoutes } from "@/features/routing/routes";
import type { Project } from "@/types/project";
import type { Asset } from "@/features/assets/types";

function makeAsset(overrides?: Partial<Asset>): Asset {
  return {
    id: "a1", name: "share.png", type: "image", mimeType: "image/png", extension: ".png",
    size: 1024,
    source: { type: "data-url", value: "data:image/png;base64,iVBORw0KGgo=" },
    createdAt: "2026-01-01T00:00:00.000Z",
    ...overrides,
  };
}

function routesOf(project: Project) {
  return computePageRoutes(project.pages);
}

function makeProject(overrides?: Partial<Project>): Project {
  return {
    id: "proj-1", name: "Test Site",
    theme: {
      palette: {
        background: "#fff", foreground: "#000", primary: "#7c5cfc",
        primaryForeground: "#fff", secondary: "#f5f5f5", secondaryForeground: "#000",
        muted: "#f5f5f5", mutedForeground: "#737373", accent: "#7c5cfc",
        accentForeground: "#fff", border: "#e5e5e5", card: "#fff", cardForeground: "#000",
      },
      typography: { fontFamily: "sans-serif", headingFont: "sans-serif", baseSize: "16px", scale: 1.25 },
      spacing: { sectionPadding: "5rem 0", containerMaxWidth: "1120px", gap: "1.5rem" },
      radius: { sm: "0.375rem", md: "0.5rem", lg: "0.75rem", xl: "1rem", full: "9999px" },
      shadows: { sm: "0 1px 2px rgba(0,0,0,0.05)", md: "0 4px 6px rgba(0,0,0,0.07)", lg: "0 10px 15px rgba(0,0,0,0.1)", xl: "0 20px 25px rgba(0,0,0,0.15)" },
    },
    assets: [],
    pages: [
      {
        id: "p1", title: "Home", slug: "/",
        sections: [
          { id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello", primaryCta: { text: "Go", href: "#" } }, styles: {} },
        ],
      },
    ],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Layout (site-level) metadata
// ---------------------------------------------------------------------------

describe("generateLayout — site-level metadata", () => {
  it("falls back to project name and a default description", () => {
    const file = generateLayout({ projectName: "My Project" });
    expect(file.path).toBe("app/layout.tsx");
    expect(file.content).toContain('title: "My Project"');
    expect(file.content).toContain('description: "Generated by Buildora"');
    expect(file.content).toContain('lang="en"');
  });

  it("emits site settings metadata when present", () => {
    const file = generateLayout({
      projectName: "My Project",
      siteSettings: {
        siteName: "Brand Name",
        siteDescription: "Tagline",
        language: "fr",
        faviconPublicPath: "/assets/icon.png",
        themeColor: "#7c5cfc",
        seoTitle: "Brand | Search Title",
      },
    });
    expect(file.content).toContain('title: "Brand | Search Title"');
    expect(file.content).toContain('description: "Tagline"');
    expect(file.content).toContain('lang="fr"');
    expect(file.content).toContain('icons: [{ rel: "icon", url: "/assets/icon.png" }]');
    expect(file.content).toContain('themeColor: "#7c5cfc"');
  });

  it("prefers seoDescription over siteDescription when only SEO is set", () => {
    const file = generateLayout({
      projectName: "P",
      siteSettings: { seoDescription: "SEO summary" },
    });
    expect(file.content).toContain('description: "SEO summary"');
  });

  it("emits robots only when the user opted out of indexing", () => {
    const hidden = generateLayout({
      projectName: "P",
      siteSettings: { robotsIndex: false },
    });
    expect(hidden.content).toContain("robots: { index: false, follow: true }");

    const defaulted = generateLayout({ projectName: "P", siteSettings: { siteName: "X" } });
    expect(defaulted.content).not.toContain("robots:");
  });

  it("escapes quotes and backslashes in metadata values", () => {
    const file = generateLayout({
      projectName: "Test",
      siteSettings: { siteName: 'He said "hi" \\ ok', seoTitle: 'Title "quoted"' },
    });
    expect(file.content).toContain('\\"');
    expect(file.content).not.toContain('title: "He said "hi""');
  });
});

// ---------------------------------------------------------------------------
// Page-level metadata
// ---------------------------------------------------------------------------

describe("generatePageFile — page-level metadata", () => {
  it("uses seoTitle for the Google title and page.title as fallback", () => {
    const project = makeProject({
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: { seoTitle: "Google Title" },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const file = generatePageFile(project, project.pages[0], routesOf(project), undefined);
    expect(file.content).toContain('title: "Google Title"');
  });

  it("falls back deterministically: seoTitle → title → page.title", () => {
    const project = makeProject();
    const file = generatePageFile(project, project.pages[0], routesOf(project), undefined);
    expect(file.content).toContain('title: "Home"');
  });

  it("emits description only when available", () => {
    const withDesc = makeProject({
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: { title: "Home", description: "A page description" },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const file = generatePageFile(withDesc, withDesc.pages[0], routesOf(withDesc), undefined);
    expect(file.content).toContain('description: "A page description"');

    const plain = makeProject();
    const plainFile = generatePageFile(plain, plain.pages[0], routesOf(plain), undefined);
    expect(plainFile.content).not.toMatch(/^  description: /m);
  });

  it("emits canonical alternates when a canonical URL is set", () => {
    const project = makeProject({
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: { canonicalUrl: "https://example.com/" },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const file = generatePageFile(project, project.pages[0], routesOf(project), undefined);
    expect(file.content).toContain('alternates: { canonical: "https://example.com/" }');
  });

  it("emits robots index:false only when the page is hidden", () => {
    const hidden = makeProject({
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: { index: false },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const file = generatePageFile(hidden, hidden.pages[0], routesOf(hidden), undefined);
    expect(file.content).toContain("robots: { index: false }");

    const plain = makeProject();
    const plainFile = generatePageFile(plain, plain.pages[0], routesOf(plain), undefined);
    expect(plainFile.content).not.toContain("robots:");
  });

  it("emits openGraph with title fallback and optional description/url/images", () => {
    const project = makeProject({
      assets: [makeAsset({ id: "share" })],
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: {
          seoTitle: "Google Title",
          description: "A page description",
          socialTitle: "Share Title",
          socialDescription: "Share desc",
          socialImage: { assetId: "share" },
          canonicalUrl: "https://example.com/",
        },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const manifest = buildExportAssetManifest(project);
    expect(manifest.valid).toBe(true);
    const file = generatePageFile(project, project.pages[0], routesOf(project), manifest);
    expect(file.content).toContain("openGraph:");
    expect(file.content).toContain('title: "Share Title"');
    expect(file.content).toContain('description: "Share desc"');
    expect(file.content).toContain('url: "https://example.com/"');
    expect(file.content).toContain('images: ["/assets/share.png"]');
  });

  it("omits social image when the asset is missing from the manifest", () => {
    const project = makeProject({
      pages: [{
        id: "p1", title: "Home", slug: "/",
        meta: { socialImage: { assetId: "missing" }, socialTitle: "T" },
        sections: [{ id: "s1", type: "hero", order: 1, visible: true, props: { headline: "Hello" }, styles: {} }],
      }],
    });
    const file = generatePageFile(project, project.pages[0], routesOf(project), undefined);
    expect(file.content).not.toContain("images:");
  });
});
