// ---------------------------------------------------------------------------
// Custom-code runtime diagnostics (Phase P23-H) — typed, sanitized, bounded
//
// A small observability model for the hardened custom-code runtime. A
// diagnostic is a structured, immutable record that describes WHAT happened
// in the runtime — never the raw data that caused it:
//
//   - `message` is a FIXED descriptive string generated by the controller
//     (e.g. "Frame ready"); it is NEVER derived from a frame payload, so
//     hostile message data can never leak into diagnostics
//   - `height` is the protocol-validated (clamped) frame height
//   - `error` is the already-sanitized RuntimeErrorInfo produced by the
//     message protocol (message/stack strings, capped) — never an arbitrary
//     exception object
//
// Diagnostics never execute anything, never carry iframe/window references,
// and are safe to inspect in tests and debugging tools.
//
// Pure, deterministic, framework-independent (no DOM access).
// ---------------------------------------------------------------------------

import { MAX_FRAME_HEIGHT_PX } from "./constants";
import type { RuntimeErrorInfo } from "./message-protocol";

/** The full set of observable runtime events. */
export type RuntimeDiagnosticKind =
  | "ready"
  | "height"
  | "error"
  | "unresponsive"
  | "recovery-started"
  | "recovery-succeeded"
  | "recovery-exhausted"
  | "disposed";

/** Hard cap on diagnostic message text (fixed descriptive strings). */
export const MAX_DIAGNOSTIC_MESSAGE_LENGTH = 160;

/**
 * One structured runtime event. Immutable — `createRuntimeDiagnostic` freezes
 * every instance so observers and snapshots can never mutate past events.
 */
export interface RuntimeDiagnostic {
  /** The runtime instance that produced this event. */
  readonly instanceId: number;
  readonly kind: RuntimeDiagnosticKind;
  /** Bounded descriptive text (never payload-derived). */
  readonly message: string;
  /** Timestamp from the runtime's safe clock. */
  readonly at: number;
  /** Present for height events (already clamped by the protocol). */
  readonly height?: number;
  /** Present for error events (already sanitized by the protocol). */
  readonly error?: RuntimeErrorInfo;
}

export interface RuntimeDiagnosticInput {
  instanceId: number;
  kind: RuntimeDiagnosticKind;
  message: string;
  at: number;
  height?: number;
  error?: RuntimeErrorInfo;
}

/** Coerce any value to a bounded diagnostic message string. */
function clampMessage(value: unknown): string {
  if (typeof value !== "string") return "";
  return value.slice(0, MAX_DIAGNOSTIC_MESSAGE_LENGTH);
}

/** Re-clamp a height defensively (the protocol already clamps). */
function clampHeight(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(Math.max(Math.round(value), 0), MAX_FRAME_HEIGHT_PX);
}

/**
 * Build a diagnostic from validated controller inputs. Message text is
 * bounded, the optional height is re-clamped defensively, and the optional
 * error is the protocol-sanitized RuntimeErrorInfo (shallow-copied so the
 * caller's object can never be mutated through the diagnostic).
 */
export function createRuntimeDiagnostic(
  input: RuntimeDiagnosticInput,
): RuntimeDiagnostic {
  const diagnostic: RuntimeDiagnostic = {
    instanceId: input.instanceId,
    kind: input.kind,
    message: clampMessage(input.message),
    at: input.at,
    ...(input.height !== undefined ? { height: clampHeight(input.height) } : {}),
    ...(input.error !== undefined ? { error: { ...input.error } } : {}),
  };
  return Object.freeze(diagnostic);
}
